### ISSUE TITLE
Repair tool for ED ships

### ISSUE THREAD

**Issue by koniecpolski** [InsideEarth2150/Update-Patch-2.3#67]
For now there is no way for repairing damaged ED ships since they are at water and Taiga/Syberia with repairibg tool can't come close enough to recover them. I recall that UCS can have small ships with the repairing tool, and LC doesn't need it so.. ED is kind of poor. When a Caspian/Wolga get hit by Ion cannon, you can't do anything to turn them back online.

**Comment by GvardianDLVII** [comment]
It works in 2.2.1.2 (aka 2.2.1.1B Alpha)
![image](https://github.com/InsideEarth2150/IEO-Updates/assets/4358600/8de4d7e8-7790-40b6-9163-4e85fce772de)
